### ISSUE TITLE
Rspamd protocol

### ISSUE THREAD

**Issue by vstakhov** [denkhaus/irspamd#1]
Hello, I'd like just to notice that rspamd uses plain `HTTP` protocol for input and hence it would be better to use a generic HTTP client than a custom client for a legacy `RSPAMC` protocol which is deprecated and might be removed in the future versions of rspamd. Moreover, the output is in the plain json now, so you could use any json parser for output processing (both learning and scanning). `--json` flag in the `rspamc` client would give you the output structure for any command desired.

**Comment by denkhaus** [comment]
Hi, thanks for the info. For scanning i use HTTP client already, but with the legacy RSPAMC protocol. 
I did not found the current HTTP command set, moreover for "learning" i took the detour via rspamc client. This can be optimized. Could you point me to the right docs? Thank you.

**Comment by vstakhov** [comment]
Unfortunately, I have no up-to-date documentation describing HTTP protocol. However, you could just dump the communication between rspamc and rspamd and grab scan and learn sequences.

**Comment by denkhaus** [comment]
Thank you for the update Vsevolod. So I'll just look into your code more in depth and figure out the protocol. Analyzing HTTP stream seems not so straightforward to me. But anyhow, thanks.

**Comment by vstakhov** [comment]
Here is the description of the current protocol: https://github.com/vstakhov/rspamd/blob/master/doc/markdown/architecture/protocol.md

**Comment by denkhaus** [comment]
Thank you for the reply. I will look into it.

**Comment by gitmonster** [comment]
@vstakhov irspamd now uses rspamc as you suggested. Close this issue.
