### ISSUE TITLE
Installation problem on arm Debian Jessie

### ISSUE THREAD

**Issue by JimboJoe** [denkhaus/irspamd#2]
Hello,

I tried to install irspamd with : go get -u github.com/denkhaus/irspamd

I ended up with these error messages:
go/src/github.com/denkhaus/irspamd/engine/engine.go:30: undefined: DataStore
go/src/github.com/denkhaus/irspamd/engine/engine.go:31: undefined: getDBPathByArgs
go/src/github.com/denkhaus/irspamd/engine/engine.go:41: undefined: NewDatastore

I use go version 1.6.2 for linux/arm.

Are there specific dependencies that are not automatically resolved, or a dependency to a specific go version?

Thanks!

**Comment by denkhaus** [comment]
Hi @JimboJoe thank you for the issue. Since the datasore is not used anymore i will push a new commit.
Hope that helps.

**Comment by JimboJoe** [comment]
That did the trick, thanks!
